const year = new Date().getFullYear();
const month = (new Date().getMonth() + 1).toString().padStart(2, '0');

export const sampleEvents = [
    {
        id: "1",
        groupId: "team-meetings",
        title: "Daily Standup Meeting",
        start: `${year}-${month}-05T10:00:00`,
        end: `${year}-${month}-05T10:30:00`,
        classNames: ["standup-event"],
        backgroundColor: "#3b82f6",
        borderColor: "#3b82f6",
        textColor: "#ffffff",
        editable: true,
        overlap: true,
        extendedProps: {
            location: "Zoom",
            description: "Daily sync with the team",
        },
    },
    {
        id: "2",
        groupId: "planning",
        title: "Sprint Planning",
        start: `${year}-${month}-10T14:00:00`,
        end: `${year}-${month}-10T15:30:00`,
        classNames: ["planning-event"],
        backgroundColor: "#10b981",
        borderColor: "#059669",
        textColor: "#ffffff",
        editable: false,
        extendedProps: {
            location: "Conference Room B",
            owner: "Scrum Master",
        },
    },
    {
        id: "3",
        title: "Company Holiday",
        start: `${year}-${month}-15`,
        allDay: true,
        display: "background",
        backgroundColor: "#f43f5e",
        borderColor: "#e11d48",
        textColor: "#ffffff",
    },
    {
        id: "4",
        groupId: "client",
        title: "Client Demo",
        start: `${year}-${month}-18T16:00:00`,
        end: `${year}-${month}-18T17:00:00`,
        url: "https://meet.google.com/demo",
        classNames: ["client-demo"],
        backgroundColor: "#f43f5e",
        borderColor: "#e11d48",
        textColor: "#ffffff",
        editable: true,
    },
    {
        id: "5",
        title: "Hackathon",
        start: `${year}-${month}-22`,
        end: `${year}-${month}-24`,
        allDay: true,
        backgroundColor: "#8b5cf6",
        borderColor: "#7c3aed",
        textColor: "#ffffff",
    },
    {
        id: "6",
        title: "Overlapping Event 1",
        start: `${year}-${month}-25T09:00:00`,
        end: `${year}-${month}-25T11:00:00`,
        backgroundColor: "#ef4444",
        overlap: false,
    },
    {
        id: "7",
        title: "Overlapping Event 2",
        start: `${year}-${month}-25T10:00:00`,
        end: `${year}-${month}-25T12:00:00`,
        backgroundColor: "#3b82f6",
        overlap: false,
    },
];